name: Build postmarketOS Rootfs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openssl tar xz-utils
          pip3 install --user git+https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git

      - name: Build postmarketOS Rootfs
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          WORK_DIR="/home/runner/work/pmbootstrap"
          mkdir -p "$WORK_DIR"
          printf "$WORK_DIR\n\nedge\nqemu\naarch64\nmainline\ndefault\n\n\n\nnone\nalways\nn\nnano,bash,gcompat,libc6-compat\n\n\n\n\n\n\n\n\n" | pmbootstrap init
          pmbootstrap --details-to-stdout install --password 147147
          ls -la "$WORK_DIR"

      - name: Create Tarball
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          WORK_DIR="/home/runner/work/pmbootstrap"
          pmbootstrap shutdown
          mkdir $HOME/work/output
          sudo findmnt -l | grep "$WORK_DIR" | awk '{print $1}' | xargs -r sudo umount -l
          cd $WORK_DIR/chroot_rootfs_qemu-aarch64
          sudo tar -cJf $HOME/work/output/postmarketos-aarch64.tar.xz .
          cd $HOME/work/output
          sudo chown $USER:$USER postmarketos-aarch64.tar.xz

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pmos-rootfs
          path: output/postmarketos-aarch64.tar.xz
      - name: Pmos Proot Image
        uses: softprops/action-gh-release@v1
        with:
          body: image of pmos for proot
          tag_name: github_run
          name: pmos proot build
          files: output/postmarketos-aarch64.tar.xz
