name: Build postmarketOS Rootfs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openssl tar xz-utils
          pip3 install --user git+https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git

      - name: Build postmarketOS Rootfs
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          WORK_DIR="/home/runner/work/pmbootstrap"
          pmbootstrap init \
            --path "$WORK_DIR" \
            --mirror-alpine "https://dl-cdn.alpinelinux.org/alpine/edge/main" \
            --repository-postmarketos "http://mirror.postmarketos.org/postmarketos/main" \
            --channel "edge" \
            --vendor "qemu" \
            --device "aarch64" \
            --ui "none" \
            --user "default" \
            --extra-packages "nano,bash,gcompat,libc6-compat"
          pmbootstrap config systemd always
          pmbootstrap --details-to-stdout install --password 147147
          mkdir -p output/postmarketos
          ls -la $WORK_DIR
          sudo cp -a "$WORK_DIR/chroot_rootfs_qemu-aarch64/." output/postmarketos/

      - name: Create Tarball
        run: |
          cd output
          tar -cJf postmarketos-aarch64.tar.xz postmarketos
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pmos-rootfs
          path: output/postmarketos-aarch64.tar.xz
      - name: Pmos Proot Image
        uses: softprops/action-gh-release@v1
        with:
          body: image of pmos for proot
          tag_name: github_run
          name: pmos proot build
          files: output/postmarketos-aarch64.tar.xz
